### ISSUE TITLE
Too many openfiles issues is not documented

### ISSUE THREAD

**Issue by EmmanuelKasper** [alvaroaleman/static-kas#20]
When running static-kas on a large must-gather with the user limit of 1024 openfiles, you run into the error:
~~~
{"error":"failed to read file namespaces/xxxx/operators.coreos.com/clusterserviceversions/jaeger-operator.v1.30.0.yaml: open namespaces/xxxxx/operators.coreos.com/clusterserviceversions/jaeger-operator.v1.30.0.yaml: too many open files"}],"stacktrace":"main.main\n\t/home/manu/Projects/git/static-kas/cmd/main.go:57\nruntime.main\n\t/usr/local/go/src/runtime/proc.go:255"
~~~

This happens with 15000 files in a must-gather 

it is easy to resolve the error by using the user hardlimit of openfiles, following 
https://www.baeldung.com/linux/error-too-many-open-files or
https://access.redhat.com/solutions/2469

however this is maybe not trivial for an end user.

If we agree to open a Wiki for the project, maybe linked from the Readme, we could add a line along the way of:

When the must-gather you process with `static-kas` has a large number of files, you may reach into an error "too many open files". In that case you will need to  [increase the maximum number of open file descriptors] for the user running static-kas(https://www.baeldung.com/linux/error-too-many-open-files).
A limit of 4096 has been found to process correctly large must-gathers.

**Comment by alvaroaleman** [comment]
This happens during discovery I presume? It might be nice to just limit the concurrency, then users don't have to configure anything
