### ISSUE TITLE
k9s "edit" button doesn't work

### ISSUE THREAD

**Issue by omertuc** [alvaroaleman/static-kas#4]
1. Type `:pods`
2. Move the cursor to some arbitrary pod
3. press <kbd>y</kbd> - works, shows you the YAML
4. press <kbd>esc</kbd> to go back
5. press <kbd>e</kbd>, should open in editor, but it doesn't

I don't want editing to literally work, obviously, the gather should be immutable, but it's really nice having the yaml open in your `$EDITOR` of your choice

Note that this is an API issue - it works OK with regular API servers

**Comment by alvaroaleman** [comment]
This happens because the server doesn't advertise the `update` verb, which is intended, as its not supported: https://github.com/alvaroaleman/static-kas/blob/e0e24ac4c999e65d0b43b0d5266b5bb1d0672317/cmd/discovery.go#L168
