### ISSUE TITLE
k9s container logs are truncated

### ISSUE THREAD

**Issue by omertuc** [alvaroaleman/static-kas#5]
1. type `:pods`
2. select an arbitrary pod
3. press <kbd>↵ Return</kbd>
4. select an arbitrary container
5. press <kbd>L</kbd>

Logs are shown, but they're truncated. Pressing <kbd>0</kbd> does not help

**Comment by alvaroaleman** [comment]
true, but it has the same issue with a real cluster. Initially, it only shows "waiting for logs".  Pressing `0` gets to the end of the log as expected. Pressing `1` shows `Stream closed EOF for podname/containername`. It seems to move somewhere, but it is not the beginning on either a real apiserver nor the static kas. Looks like the tool is just buggy.
